### ISSUE TITLE
AES-CTR is unauthenticated

### ISSUE THREAD

**Issue by codahale** [LuminalOSS/credstash#1]
First off, as an author of a [similar utility](https://github.com/codahale/sneaker) congrats on your impeccable taste. :)

My one piece of feedback is that AES-CTR is trivially malleable, which is to say an attacker can modify the ciphertext and change the resulting plaintext without anyone noticing. I would strongly suggest using an authenticated mode like GCM, CCM, OCB, etc. or an Encrypt-Then-MAC construction with HMAC-SHA256 and an independent key.

**Comment by a5an0** [comment]
I hadn't seen sneaker, I'll have to check that out!

Thanks for the feedback. I agree that the ciphertext needs to be authenticated to protect from an attacker that has access to DDB, but not the keys in KMS. AES-GCP would be an easy one-and-done solution, but pycrypto doesn't support it. I am looking at generating a second key for each item to be stored, and using that to HMAC the ciphertext, and then wrapping the HMAC key in the KMS key as well (if it's not wrapped, and is just in DDB, then it does us no good, as an attacker with access to DDB could modify the ciphertext and then generate a valid HMAC for it). 

If an attacker has access to DDB and the key in KMS, there's not really anything we can do.

**Comment by codahale** [comment]
Instead of two separate data keys, you could generate a longer data key and split it yourself.

--
Coda Hale

**Comment by a5an0** [comment]
Currently, I'm having KMS generate data keys for me (VMs dont have good sources of entropy). I may eventually get some random from KMS (via GenerateRandom()) and use that to see a prng and generate my own heys, but for now, its keys from KMS. As far as I can tell, the KMS call to generate a data key maxes out at 32 bytes, so I'm just getting two keys from KMS, one for data and one for HMAC.

The PR for doing the HMAC is linked in this issue. If you want to provide any feedback, you are more then welcome.

**Comment by a5an0** [comment]
I'm going to go ahead and close this issue. If you have any other feedback or issues, let us know!

**Comment by codahale** [comment]
The maximum size for the `NumberOfBytes` parameter on the `GenerateDataKey` API call is 1024 bytes, so you should be able to pass `number_of_bytes=64` rather than `key_spec="AES_256"` and then split that key into two 256-bit subkeys.

**Comment by a5an0** [comment]
cool! I did not know that you could generate a data key that large. I'll check that out.

**Comment by a5an0** [comment]
@codahale thanks for the tip. implemented in #4. Much prefer 1 call to KMS instead of two :)
