### ISSUE TITLE
credstash setup doesn't respect region

### ISSUE THREAD

**Issue by sid137** [LuminalOSS/credstash#15]
Hi,

When trying to create the dynamodb table in eu-west-1 (credstash -r eu-west-1 setup), I see that it still gets created in N. Virginia.

It would be nice if it could use the AWS_DEFAULT_REGION env var by default

**Comment by a5an0** [comment]
thanks for reporting this. A fix for the setup function and checking for the env var are both in #16.

**Comment by a5an0** [comment]
fixed. you can now either use the `-r` flag or `$AWS_DEFAULT_REGION`.
