### ISSUE TITLE
Add support for Encryption Contexts

### ISSUE THREAD

**Issue by gene1wood** [LuminalOSS/credstash#17]
In order to be able to provide access control to the credentials stored by credstash (somewhat like what's requested in Issue #13), credstash needs to be able to pass [Encryption Contexts](http://docs.aws.amazon.com/kms/latest/developerguide/encrypt-context.html) to the KMS API with `get` and `put` requests.

Doing so will allow for the creation of both [KMS Key Policies](http://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html) and [KMS Grants](http://docs.aws.amazon.com/kms/latest/developerguide/grants.html) which constrain access to specific credentials.

I've put together PR #18 to provide this added functionality.

**Comment by a5an0** [comment]
merged
