### ISSUE TITLE
New argparse subparser for `put` break `-i` INFILE option

### ISSUE THREAD

**Issue by gene1wood** [LuminalOSS/credstash#19]
I'm sorry, my change to using subparsers conflicts with the way the `-i INFILE` option works.

Previously, the `value` argument for the `put` action was optional. This got around the fact that it was only used for `put` (and not `get`, `list`, etc) and that the value might be empty if the `-i` option was used.

Currently at credstash 1.3.1 if you execute

```
credstash put -i /etc/hosts myhostsfile
```

It will fail because it's expecting a value argument after `myhostfile`

So, fixes for this 
* We could add some fancy logic that changes the `value` to optional and ignores it if the `-i` argument is present. This sounds ugly.
* We could move to using the argument syntax found in [curl](http://curl.haxx.se/docs/manpage.html) where when a value beings with the `@` character, it indicates that the value is not a value but instead a filename to the file containing the value. This can be seen in curl options like `--data`, `--form`, `--write-out` and others. This solves the problem, but isn't backwards compatible. Anyone already using the `-i` syntax to pass file contents in as a value would stop working.
* Some other fix I'm not thinking of

I'm happy to code this up (as the bug is my fault), but I want to find out what direction to go in first.

**Comment by gene1wood** [comment]
Another option would be to say if the `value` equals `-` then the value is taken from `stdin`. This behavior can be seen in tools like `cat` and `less`.

The result would be that to `put` a file you'd run

```
cat www.example.com.key | credstash put ssl_certificate_private_key -
```

**Comment by gene1wood** [comment]
In case you like the `@` syntax solution, I've made PR #20 to unblock unrelated work I'm doing.

**Comment by a5an0** [comment]
merged
