### ISSUE TITLE
Version isn't constrained to a numeric value

### ISSUE THREAD

**Issue by gene1wood** [LuminalOSS/credstash#26]
The version field can be any value. The [logic to get the latest version](https://github.com/LuminalOSS/credstash/blob/f9b8cfe9d92e99a7ef3153765b80a4ba59f17aea/credstash.py#L164) may cause confusing results when non-numeric versions are used.

We could constrain this at the argument level, or the dynamodb field level, or both (probably better), or leave it like it is. Thoughts?

**Comment by a5an0** [comment]
This was actually intentional. My thought was that while I like using monotonically incrementing ints for versions, someone else might want to do semantic versions, or names of cheeses, or some other versioning scheme that makes sense to them. As long as it's lexicographical increasing over time, the "get latest version" code should work.

Thoughts?

**Comment by gene1wood** [comment]
That makes good sense, just wanted to make sure.

I encountered this while rushing. I did a put and got the error "[foo version 1 is already in the credential store. Use the -v flag to specify a new version](https://github.com/LuminalOSS/credstash/blob/909a707860f1823c34b4f7c45530b3d0e56fa99e/credstash.py#L294)" so I ran it again adding "-v" (but not thinking to explicitly add a version, assuming it would autoincrement).

`arparse` forgivingly accepted the input assuming my credential name was my version, my secret was my credential name and my first context was my secret. The downsides to accepting any type of value for version, credential name and secret.

**Comment by gene1wood** [comment]
Oh also, one thing I'm noticing from that error message, if you've got 3 versions in the store, and you try to `put` a 4th without specifying the `-v` argument the message would be

```
foo version 1 is already in the credential store. Use the -v flag to specify a new version
```

which is true, but a bit odd in that there would also be versions `2` and `3` (assuming normal integer numbering).

**Comment by a5an0** [comment]
that is odd. I'll take a look

**Comment by a5an0** [comment]
ok, so here's the line that generates the message:
```
        except ConditionalCheckFailedException:
            printStdErr("%s version %s is already in the credential store. Use the -v flag to specify a new version" % (args.key, args.version if args.version != "" else "1"))
```
So if the user hasn't passed a version, it just assumes that it's version 1. The only way we'd be able to know what the highest version actually is is to query the table. 

I've been thinking about this a bunch, and I'm hesitant to use some read throughput just to generate a better error message. If we don't want to consume additional throughput, then the answer is to change the error message. If the user specified the version, we tell them that it's already in DDB; if they haven't, we tell them there are already records in the database. The either pick a version, or they do a `list`, and pick a version.

However, I can see it getting very old to just get back error messages where you see "this is already there. try again", at which point you have to do a `list` to pick a new version number. In that case, it's actually more expensive to list everything to pick a new version number than it would have been to just do a query and generate a better error message.

With all that in mind, I'm going to make a change to have the error message have the latest version that's in the DB.

PR coming...

Thoughts?

**Comment by a5an0** [comment]
The PR to that effect is https://github.com/LuminalOSS/credstash/pull/28

**Comment by jt7d** [comment]
If a given key exists in versions 1,2,3,4,5,6,7,8,9,10,11 then won't "latest" be 9?
