### ISSUE TITLE
Check out Sneaker

### ISSUE THREAD

**Issue by gene1wood** [LuminalOSS/credstash#30]
Here is a go implementation of something similar to credstash : [sneaker](https://github.com/codahale/sneaker)

It may make sense to take a look at it and see if there are any ideas that we should use from it.

**Comment by a5an0** [comment]
I've been meaning to look into KMS master key rotation, but I _really_ like the key rotation command that's in sneaker: https://github.com/codahale/sneaker/blob/master/rotate.go
For credstash, it would just be a matter of `get`-ing and then `put`-ing a secret (or secrets if we wildcard or `getall` them).

**Comment by a5an0** [comment]
Another neat thing that we should borrow is setting the KMS master key via env variable. credstash can select the kms key via cli argument, but being able to set an ENV variable as well would be cool
