### ISSUE TITLE
Set release to latest code in master / update pip repository

### ISSUE THREAD

**Issue by chothia** [LuminalOSS/credstash#49]
Hi,

I was wondering if it's possible to get the latest version of master as a new release available through pip?

I was trying to get the --autoversion working, but I realized the version I have is 1.5.2 which does not contain that feature.

Thanks

**Comment by alex-luminal** [comment]
Right you are! I just pushed v1.6 to pypi

**Comment by alex-luminal** [comment]
you should be able to upgrade with `pip install --upgrade credstash`

**Comment by chothia** [comment]
Thanks, it works great!!!
